"""HTTP routes for Blog Post Writer features."""

from fastapi import APIRouter, BackgroundTasks, Depends, File, HTTPException, UploadFile

from core.auth.dependencies import get_current_user
from core.auth.schemas import AuthenticatedUser
from core.auth.service import parse_user_id
from labs.agents.service import LabPostService

router = APIRouter(
    prefix="/labs",
    tags=["Blog Post Writer"],
    dependencies=[Depends(get_current_user)],
)
outputs_router = APIRouter(
    prefix="/outputs",
    tags=["Outputs"],
    dependencies=[Depends(get_current_user)],
)
service = LabPostService()


@router.post("/review")
async def review(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    user: AuthenticatedUser = Depends(get_current_user),
) -> dict[str, str]:
    """Transform markdown notes into a structured blog post."""
    raw_content = await file.read()
    try:
        context = raw_content.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise HTTPException(status_code=400, detail="File must be UTF-8 encoded.") from exc

    return await service.enqueue_markdown_organization(
        background_tasks=background_tasks,
        filename=file.filename or "",
        context=context,
        user_id=parse_user_id(user),
    )


@outputs_router.get("/makdown")
async def list_markdown_outputs() -> dict[str, object]:
    """List markdown outputs generated by the service."""
    return service.list_markdown_outputs()


@outputs_router.get("/pdf")
async def list_pdf_outputs() -> dict[str, object]:
    """List PDF outputs generated by the service."""
    return service.list_pdf_outputs()
