"""HTTP routes for Blog Post Writer features."""

from uuid import UUID

from fastapi import APIRouter, BackgroundTasks, Depends

from core.auth.dependencies import get_current_user
from core.auth.schemas import AuthenticatedUser
from core.auth.service import parse_user_id
from labs.agents.service import LabPostService

router = APIRouter(
    prefix="/labs",
    tags=["Blog Post Writer"],
    dependencies=[Depends(get_current_user)],
)
outputs_router = APIRouter(
    prefix="/outputs",
    tags=["Outputs"],
    dependencies=[Depends(get_current_user)],
)
service = LabPostService()


@router.post("/review/{process_status_id}")
async def review(
    background_tasks: BackgroundTasks,
    process_status_id: UUID,
    user: AuthenticatedUser = Depends(get_current_user),
) -> dict[str, str]:
    """Transform stored process notes into a structured blog post."""
    return await service.enqueue_markdown_organization_for_process(
        background_tasks=background_tasks,
        process_status_id=process_status_id,
        user_id=parse_user_id(user),
    )


@outputs_router.get("/makdown")
async def list_markdown_outputs() -> dict[str, object]:
    """List markdown outputs generated by the service."""
    return service.list_markdown_outputs()


@outputs_router.get("/pdf")
async def list_pdf_outputs() -> dict[str, object]:
    """List PDF outputs generated by the service."""
    return service.list_pdf_outputs()
