"""HTTP routes for Blog Post Writer features."""

from fastapi import APIRouter, BackgroundTasks, File, HTTPException, UploadFile

from labs.agents.labs_reviewer.schema import LabReviewerRequest, LabReviewerResponse
from labs.service import LabPostService

router = APIRouter(prefix="/labs", tags=["Blog Post Writer"])
outputs_router = APIRouter(prefix="/outputs", tags=["Outputs"])
service = LabPostService()


@router.post("/review")
async def review(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
) -> dict[str, str]:
    """Transform markdown notes into a structured blog post."""
    raw_content = await file.read()
    try:
        context = raw_content.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise HTTPException(status_code=400, detail="File must be UTF-8 encoded.") from exc

    return service.enqueue_markdown_organization(
        background_tasks=background_tasks,
        filename=file.filename or "",
        context=context,
    )


@outputs_router.get("/makdown")
async def list_markdown_outputs() -> dict[str, object]:
    """List markdown outputs generated by the service."""
    return service.list_markdown_outputs()


@outputs_router.get("/pdf")
async def list_pdf_outputs() -> dict[str, object]:
    """List PDF outputs generated by the service."""
    return service.list_pdf_outputs()
